# baseURL                   = "https://luchanworld.com"
baseURL                   = "https://jovial-pare-3fc1e9.netlify.com"
builddrafts                = false
languageCode               = "en-us"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 3

theme                      = "AllinOne"
title                      = "Luchanworld"

pygmentsuseclasses         = true


[permalinks]
  blog                     = "blog/:year-:month/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Blog"
    weight                 = -120
    identifier             = "blog"
    url                    = "blog/"  

  [[menu.main]]
    name                   = "Moment"
    weight                 = -110
    identifier             = "moment"
    url                    = "moment/" 

  [[menu.main]]
    name                   = "About"
    weight                 = -100
    identifier             = "about"
    url                    = "about/"  

 

[params]
  faviconfile              = "img/chino.jpg"               # from static/
  avatar                   = "img/estelogo.jpg"             # path to image in static dir e.g img/avatar.png 
  author                   = "Luchanworld"
  description              = ["Be myself.", "Love the wonderful world.", "Do the right things and be a better human."]           # appears in the site header when set to a non-empty string
  welcome_head             = "Hello, World!"
  welcome_word             = "~ Warriors Traveling ~"

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "you@email.com"
  github                   = "//github.com/you"
  #linkedin                 = "//linkedin.com/in/you"
  facebook                 = "//facebook.com/maria.lujannavarro.39"
  youtube                  = "//youtube.com/channel/UCNAdGZDRYSLPPtKS9KZNYdA?view_as=subscribe"
  twitter                  = "//twitter.com/?lang=en" 
  instagram                = "//instagram.com/Luchanworld"
  include_rss              = true                          # include RSS <link> tag in <head> and show RSS icon
  
  # analytics
  googleAnalytics          = "your-google-analytic-id"